src/config/routes.rb
# frozen_string_literal: true

# This file tells the Rails server how incoming requests are sent to which
# controller and method.
#
#
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :events
  resources :timelines
  resources :submissions
  resources :companies
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'
  root 'home#index'
  post '/companies/:id', to: 'companies#timeline', as: "company_timeline"
  post '/submissions/:id', to: 'submissions#approve', as: "approve_submission" #routes for custom functions
  # Devise authentification pages. This controlls the user login
  # and authentification system.
  devise_for :users

  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  #
  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'
end

src/app/controllers/home_controller.rb
# frozen_string_literal: true

# Controller for the home page already made for you
class HomeController < ApplicationController
  # No sign in needed to access these pages
  # Overrides ApplicationController's instructions to check for login by default
  skip_before_action :authenticate_user!

  # GET /
  #
  # This method is empty, yet it works?
  # Rails controller methods can be completely empty and work just fine.
  # It's the name of the method matching to a html.erb file that
  # makes the link between the files.
  # Find me @ app/views/home/index.html.erb
  #
  # Also, any local variable made inside this method will also exist
  # in the view to be displayed. Do not look up information within the
  # view itself. Do it here, please!
  def index; end
end

src/app/helpers/home_helper.rb
# frozen_string_literal: true

# Helper methods accessable for views within the home folder
module HomeHelper
end

src/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%# header for navigation %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'The World\'s Worst', root_path, class:"navbar-brand" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Company List', companies_path, class:"nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Add Company', new_company_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'View Submissions', submissions_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add Event', new_event_path, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Add Submission', new_submission_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav">
          <%# If user, show account, else sign in %>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
                Account
              </a>
              <%# Change to rails "link_to" for the actual links when implementing %>
              <%# Make sure to include the css class as shown in the login example %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%# The rails administration panel link %>
                <% if Rails.env.development? %><%= link_to 'Rails Admin', rails_admin_path, class: "dropdown-item" %><% end %>
                <div class="dropdown-divider"></div>
                <%# Devise requires that the logout command be sent using the 'delete' HTTP verb (method) %>
                <%= link_to "Logout", destroy_user_session_path, class: "dropdown-item", method: :delete %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= button_to "Login", new_user_session_path, class: "btn btn-outline-primary" %>
            </li>
          <% end %>
        </ul>
  </div>
</nav>

src/app/views/home/index.html.erb
<div class = "container-md">
  <body>
    <h1>The World's Worst</h1>
    <p>
      Companies and corporations have seen unprecedented growth since the turn of the 20th century. Where once business was all privately owned, 
      and the loyalty of the company was to the people, many companies have since gone both global and public, with their loyalties now lying only with themselves.
      These entities now have power that rivals and even exceeds some governments, and they use their power to generate as much revenue for themselves as possible,
      regardless of the damage they do to societies and populations across the globe. My hope is that this program can both be informative and interactive,
      educating people about a serious threat to us that the media rarely, if ever covers.
    </p>
    <h3>Features</h3>
    <p>
      Some of the features of this program include:
      <ul>
        <li>An interactive list of companies, each with CRUD capability as well as association with their respective timelines.</li>
        <li>A search feature for the different companies</li>
        <li>The ability for users to submit their own companies to be included in the database</li>
        <li>An admin system that allows admins to approve / deny / edit submissions made by users</li>
        <li>A better looking user experience thanks to Bootstrap</li>
        <li>A basic layout, user logins, and other features already provided by the graces of Dr. Pulimood</li>
      </ul>
    </p>
    <h3>Upload Company</h3>
    <p>A main feature of this website is the communal uploading of information similar to wikipedia, or in this case something more similar to wikileaks. Try it out!</p>
    <%= link_to 'Add an entry to our database', companies_path, class:"btn btn-dark" %>
    <br><br>
    <h3>How to Run (For Admins)</h3>
    <p>Run rake db:migrate:reset, then rake db:create, and finally rails db:seed</p>
    <br>
    <h3>Special Thanks</h3>
    <p>I would like to thank Dr Pulimood for approving my project, as well as the help she and Kiera Gill gave me throughout the project. <br> In addition, I would like to thank the many underground sources of media / news that I subscribe to, as they are the groups that convinced me to make this program. <br> While I'm not comfortable naming names, those who know, know.</p>
  </body>
</div>