src/config/routes.rb
# frozen_string_literal: true

# This file tells the Rails server how incoming requests are sent to which
# controller and method.
#
#
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :events
  resources :timelines
  resources :submissions
  resources :companies
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'
  root 'home#index'
  post '/companies/:id', to: 'companies#timeline', as: "company_timeline"
  post '/submissions/:id', to: 'submissions#approve', as: "approve_submission" #routes for custom functions
  # Devise authentification pages. This controlls the user login
  # and authentification system.
  devise_for :users

  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  #
  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'
end

src/app/models/company.rb
class Company < ApplicationRecord
    has_many :events #model association to events

    def self.searchName(params)
        if params #if there is parameters
            where('name LIKE ?', "%#{params}%") #search where name is like params using SQL's LIKE command
        else #else if there are no parameters
            where('id != 0') #load all the companies without id of zero
        end
      end
      
end

src/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies or /companies.json
  def index
    @companies = Company.all 
    @companies = @companies.searchName(params[:search])
    @companies = @companies.where('id != 0') # shows every company except the one seeded with an ID of 0
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  def timeline #controller for timeline page
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to company_url(@company), notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :description, :industry, :country)
    end
end

src/app/helpers/companies_helper.rb
module CompaniesHelper
end

src/app/views/companies/_form.html.erb
 <%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div>
    <%= form.text_field :name, class: "form-control", placeholder: "Company Name" %>
  </div>
  <br>
  <div>
    <%= form.text_field :description, class: "form-control", placeholder: "Description" %>
  </div>
  <br>
  <div>
    <%= form.text_field :industry, class: "form-control", placeholder: "Type of Company / Industry" %>
  </div>
  <br>
  <div>
    <% form.label :country, style: "display: block", class: "field form-group" %>
    <%= form.text_field :country, class: "form-control", placeholder: "Country of Origin" %>
  </div>
  <br>
  <div>
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

src/app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

src/app/views/companies/index.html.erb
<h1>Companies</h1>
<%= form_tag companies_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:input] %>
    <%= submit_tag "Search Name", :name => nil %>
  </p>
<% end %>

<table class="table table-striped table-light table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Industry</th>
      <th>Country</th>
    </tr>
  </thead>
  <!-- company info with link for timeline-->
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.description %></td>
        <td><%= company.industry %></td>
        <td><%= company.country %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'View Timeline', company_timeline_path(company), method: :post %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>
<br>

src/app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

src/app/views/companies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @company.description %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @company.industry %>
</p>

<p>
  <strong>Country:</strong>
  <%= @company.country %>
</p>
<br>
<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

src/app/views/companies/timeline.html.erb
<!--Basic page for rendering timeline, was not completed in time-->
<% company = Company.find(params[:id]) %>
<p> <%= company.name %></p>

<p>Timeline:</p>
<ul>
  <% company.events.each do |event| %>
    <li><%= event.title %></li>
  <% end %>
</ul>